// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6kXZYG3UlD9Hmx3ImNsuqGJdYwxkGGbw',
    appId: '1:628244631095:web:57a019fdbc64c53a7979b2',
    messagingSenderId: '628244631095',
    projectId: 'mood-diary-app-8a370',
    authDomain: 'mood-diary-app-8a370.firebaseapp.com',
    storageBucket: 'mood-diary-app-8a370.firebasestorage.app',
    measurementId: 'G-5HDR51ENET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPpv6G6KKohxwdX56WMREg0eg-x7P285M',
    appId: '1:628244631095:android:98bfddf65e0ae4e47979b2',
    messagingSenderId: '628244631095',
    projectId: 'mood-diary-app-8a370',
    storageBucket: 'mood-diary-app-8a370.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6lAYWbZJ0vmyh4jsjJEkbjgPv63OHht0',
    appId: '1:628244631095:ios:1ec85bc2e829308b7979b2',
    messagingSenderId: '628244631095',
    projectId: 'mood-diary-app-8a370',
    storageBucket: 'mood-diary-app-8a370.firebasestorage.app',
    iosBundleId: 'com.example.moodDiaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6lAYWbZJ0vmyh4jsjJEkbjgPv63OHht0',
    appId: '1:628244631095:ios:1ec85bc2e829308b7979b2',
    messagingSenderId: '628244631095',
    projectId: 'mood-diary-app-8a370',
    storageBucket: 'mood-diary-app-8a370.firebasestorage.app',
    iosBundleId: 'com.example.moodDiaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6kXZYG3UlD9Hmx3ImNsuqGJdYwxkGGbw',
    appId: '1:628244631095:web:2658077905c768847979b2',
    messagingSenderId: '628244631095',
    projectId: 'mood-diary-app-8a370',
    authDomain: 'mood-diary-app-8a370.firebaseapp.com',
    storageBucket: 'mood-diary-app-8a370.firebasestorage.app',
    measurementId: 'G-KJ5ZBNXSFL',
  );

}